In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Datasets/oil_prices.csv')

In [ ]:
#First 5 entries of the dataset
df.head(5)

,Date,day,month,year,Price,Open,High,Low,Vol1,Vol,change
0,01/12/2022,1,12,2022,86.88,86.78,89.37,86.26,229.13K,229.13,1.70%
1,30/11/2022,30,11,2022,85.43,83.77,85.67,83.61,9.05K,9.05,2.89%
2,29/11/2022,29,11,2022,83.03,82.41,86.00,82.39,67.93K,67.93,-0.19%
3,28/11/2022,28,11,2022,83.19,83.58,84.10,80.61,102.56K,102.56,-0.53%
4,25/11/2022,25,11,2022,83.63,85.50,86.87,83.59,85.31K,85.31,-2.00%

In [ ]:
# Last 5 entries of the dataset
df.tail(5)

,Date,day,month,year,Price,Open,High,Low,Vol1,Vol,change
2578,07/12/2012,7,12,2012,107.02,107.05,107.89,106.66,181.18K,181.18,-0.01%
2579,06/12/2012,6,12,2012,107.03,108.63,109.16,106.63,215.28K,215.28,-1.64%
2580,05/12/2012,5,12,2012,108.81,109.87,110.57,108.64,184.65K,184.65,-0.94%
2581,04/12/2012,4,12,2012,109.84,110.92,110.92,109.15,213.91K,213.91,-0.97%
2582,03/12/2012,3,12,2012,110.92,110.96,112.33,110.60,195.73K,195.73,-0.28%

In [ ]:
# Data filtering
df.loc[:,["year","Price"]]

      year   Price
0     2022   86.88
1     2022   85.43
2     2022   83.03
3     2022   83.19
4     2022   83.63
...    ...     ...
2578  2012  107.02
2579  2012  107.03
2580  2012  108.81
2581  2012  109.84
2582  2012  110.92

[2583 rows x 2 columns]

In [ ]:
#Selecting few(10) rows
df.loc[0:10,:]

,Date,day,month,year,Price,Open,High,Low,Vol1,Vol,change
0,01/12/2022,1,12,2022,86.88,86.78,89.37,86.26,229.13K,229.13,1.70%
1,30/11/2022,30,11,2022,85.43,83.77,85.67,83.61,9.05K,9.05,2.89%
2,29/11/2022,29,11,2022,83.03,82.41,86.00,82.39,67.93K,67.93,-0.19%
3,28/11/2022,28,11,2022,83.19,83.58,84.10,80.61,102.56K,102.56,-0.53%
4,25/11/2022,25,11,2022,83.63,85.50,86.87,83.59,85.31K,85.31,-2.00%
5,24/11/2022,24,11,2022,85.34,85.04,85.54,83.90,75.61K,75.61,-0.08%
6,23/11/2022,23,11,2022,85.41,88.47,89.56,84.12,212.14K,212.14,-3.34%
7,22/11/2022,22,11,2022,88.36,87.76,89.90,87.35,190.85K,190.85,1.04%
8,21/11/2022,21,11,2022,87.45,87.74,87.98,82.31,354.60K,354.60,-0.19%
9,18/11/2022,18,11,2022,87.62,90.10,90.63,85.80,379.66K,379.66,-2.41%
10,17/11/2022,17,11,2022,89.78,92.73,92.91,89.53,313.53K,313.53,-3.32%

In [ ]:
# selecting only specified row
df.loc[(df.year==2021) & (df.month==12),:]

,Date,day,month,year,Price,Open,High,Low,Vol1,Vol,change
238,31/12/2021,31,12,2021,77.78,78.81,79.68,77.55,148.96K,148.96,-1.94%
239,30/12/2021,30,12,2021,79.32,79.19,79.66,78.50,10.90K,10.90,0.11%
240,29/12/2021,29,12,2021,79.23,79.28,80.17,78.13,69.63K,69.63,0.37%
241,28/12/2021,28,12,2021,78.94,78.67,79.85,78.48,50.41K,50.41,0.43%
242,27/12/2021,27,12,2021,78.60,76.32,79.08,75.75,85.39K,85.39,3.23%
243,24/12/2021,24,12,2021,76.14,76.72,76.79,75.75,30.54K,30.54,-0.92%
244,23/12/2021,23,12,2021,76.85,75.47,77.00,74.78,161.24K,161.24,2.07%
245,22/12/2021,22,12,2021,75.29,74.05,75.67,73.62,166.71K,166.71,1.77%
246,21/12/2021,21,12,2021,73.98,71.88,74.27,71.24,214.07K,214.07,3.44%
247,20/12/2021,20,12,2021,71.52,72.82,72.87,69.28,333.76K,333.76,-2.72%
248,17/12/2021,17,12,2021,73.52,74.50,74.98,72.65,231.41K,231.41,-2.00%
249,16/12/2021,16,12,2021,75.02,74.47,75.61,74.00,223.64K,223.64,1.54%
250,15/12/2021,15,12,2021,73.88,73.25,74.58,72.50,233.19K,233.19,0.24%
251,14/12/2021,14,12,2021,73.70,74.42,75.16,72.57,277.86K,277.86,-0.93%
252,13/12/2021,13,12,2021,74.39,75.37,76.39,74.20,265.51K,265.51,-1.01%
253,10/12/2021,10,12,2021,75.15,73.99,75.71,73.80,221.36K,221.36,0.98%
254,09/12/2021,9,12,2021,74.42,75.94,76.70,73.84,283.39K,283.39,-1.85%
255,08/12/2021,8,12,2021,75.82,75.44,76.37,74.38,322.08K,322.08,0.50%
256,07/12/2021,7,12,2021,75.44,73.60,76.27,73.20,312.28K,312.28,3.23%
257,06/12/2021,6,12,2021,73.08,70.24,73.80,70.24,255.40K,255.40,4.58%
258,03/12/2021,3,12,2021,69.88,70.22,72.62,69.24,331.82K,331.82,0.30%
259,02/12/2021,2,12,2021,69.67,69.72,70.70,65.72,526.60K,526.60,1.16%
260,01/12/2021,1,12,2021,68.87,69.80,72.87,68.14,420.40K,420.40,-2.41%

In [ ]:
# selecting rows with null values
df.loc[df.isnull().any(axis=1),:]

,Date,day,month,year,Price,Open,High,Low,Vol1,Vol,change
60,08/09/2022,8,9,2022,88.62,87.98,89.82,87.25,NaN,#VALUE!,0.70%
1529,02/01/2017,2,1,2017,56.82,56.82,56.82,56.82,NaN,#VALUE!,0.00%
2304,01/01/2014,1,1,2014,110.92,110.92,110.92,110.92,NaN,#VALUE!,0.11%

In [ ]:
df.loc[df['Vol'].isnull(),:]

Empty DataFrame
Columns: [Date, day, month, year, Price, Open, High, Low, Vol1, Vol, change]
Index: []

In [ ]:
# counting number of null values
df['Vol'].isnull().sum()

np.int64(0)

In [ ]:
df.describe()

,day,month,year,Price,Open,High,Low
count,2583.000000,2583.000000,2583.000000,2583.000000,2583.000000,2583.000000,2583.000000
mean,15.724739,6.530778,2017.423539,71.279524,71.283519,72.257921,70.254433
std,8.776140,3.435434,2.885677,24.313593,24.289734,24.422220,24.142475
min,1.000000,1.000000,2012.000000,19.330000,19.900000,21.290000,15.980000
25%,8.000000,4.000000,2015.000000,51.850000,51.845000,52.590000,51.150000
50%,16.000000,7.000000,2017.000000,65.320000,65.280000,66.180000,64.500000
75%,23.000000,10.000000,2020.000000,92.740000,92.665000,94.235000,91.155000
max,31.000000,12.000000,2022.000000,127.980000,130.280000,139.130000,122.500000